Attribute VB_Name = "modSelfTest"
Option Explicit

' Offline self-test harness: replays the golden vectors (tests\vectors\)
' against the deterministic VBA logic, with ZERO Word dependency -- Excel and
' the filesystem only. The vectors are generated by the Python reference twin
' (ref/ + tests/vectors/regenerate.py); if every case passes, the VBA
' transliteration agrees with the twin.
'
' Operator loop: import the .bas modules -> run RunAllSelfTests -> paste
' selftest_report.txt back to the developer. Green before the first real run.
'
' Vector escape rule (reversed by VectorUnescape below):
'   \t tab, \n LF, \r CR, \\ backslash, \uXXXX UTF-16 code unit (4 hex).
'   Everything else is literal printable ASCII, so native line I/O is safe.

Private Const SUITE_FINGERPRINT As String = "fingerprint"
Private Const SUITE_PARSER As String = "parser"
Private Const SUITE_SESSION As String = "session"
Private Const SUITE_COVERAGE As String = "coverage"

' Module-level result accumulators (reset per run)
Private mResultsRow As Long
Private mReport As String
Private mSuitePass As Long
Private mSuiteFail As Long

Public Sub RunAllSelfTests()
    Dim wsOut As Worksheet
    Dim vecDir As String
    Dim totalPass As Long
    Dim totalFail As Long
    Dim summary As String
    Dim reportPath As String
    Dim f As Integer

    vecDir = ThisWorkbook.Path & "\tests\vectors\"
    If Len(Dir$(vecDir, vbDirectory)) = 0 Then
        MsgBox "Vector folder not found:" & vbCrLf & vecDir & vbCrLf & vbCrLf & _
               "Copy the repo's tests\vectors\ folder next to this workbook, " & _
               "then run again.", vbExclamation, "Self Test"
        Exit Sub
    End If

    Set wsOut = EnsureSelfTestSheet()
    mResultsRow = 2
    mReport = "AutoReviewer self-test report -- " & Format$(Now, "yyyy-mm-dd hh:nn:ss") & vbCrLf & _
              "Workbook: " & ThisWorkbook.name & vbCrLf & _
              "Vectors:  " & vecDir & vbCrLf & vbCrLf

    summary = ""

    mSuitePass = 0: mSuiteFail = 0
    RunFingerprintSuite wsOut, vecDir & "fingerprint_vectors.txt"
    summary = summary & SuiteSummaryLine(SUITE_FINGERPRINT)
    totalPass = totalPass + mSuitePass: totalFail = totalFail + mSuiteFail

    mSuitePass = 0: mSuiteFail = 0
    RunParserSuite wsOut, vecDir & "parser_vectors.txt"
    summary = summary & SuiteSummaryLine(SUITE_PARSER)
    totalPass = totalPass + mSuitePass: totalFail = totalFail + mSuiteFail

    mSuitePass = 0: mSuiteFail = 0
    RunSessionSuite wsOut, vecDir & "session_vectors.txt"
    summary = summary & SuiteSummaryLine(SUITE_SESSION)
    totalPass = totalPass + mSuitePass: totalFail = totalFail + mSuiteFail

    mSuitePass = 0: mSuiteFail = 0
    RunCoverageSuite wsOut, vecDir & "coverage_vectors.txt"
    summary = summary & SuiteSummaryLine(SUITE_COVERAGE)
    totalPass = totalPass + mSuitePass: totalFail = totalFail + mSuiteFail

    summary = summary & vbCrLf & "TOTAL: " & totalPass & " passed, " & totalFail & " failed -- " & _
              IIf(totalFail = 0, "OVERALL: GREEN", "OVERALL: RED") & vbCrLf

    ' Summary block on the sheet
    mResultsRow = mResultsRow + 1
    wsOut.Cells(mResultsRow, 1).value = "SUMMARY"
    wsOut.Cells(mResultsRow, 2).value = summary
    wsOut.Cells(mResultsRow, 1).Font.Bold = True
    wsOut.Columns("A:F").EntireColumn.AutoFit
    wsOut.Columns("C:E").ColumnWidth = 60

    mReport = mReport & vbCrLf & summary

    ' Plain-text report next to the workbook: this file is what the operator
    ' pastes back. ASCII by construction (previews stay in escaped form).
    reportPath = ThisWorkbook.Path & "\selftest_report.txt"
    On Error Resume Next
    f = FreeFile
    Open reportPath For Output As #f
    Print #f, mReport
    Close #f
    On Error GoTo 0

    MsgBox summary & vbCrLf & "Report written to:" & vbCrLf & reportPath, _
           IIf(totalFail = 0, vbInformation, vbCritical), "Self Test"
End Sub

'=== Suites ==========================================================

Private Sub RunFingerprintSuite(ByVal wsOut As Worksheet, ByVal path As String)
    Dim dataLines As Collection
    Dim raw As Variant
    Dim cols() As String
    Dim caseNum As Long
    Dim inputStr As String
    Dim expected As String
    Dim actual As String

    Set dataLines = ReadVectorLines(path)
    If dataLines Is Nothing Then
        WriteResult wsOut, SUITE_FINGERPRINT, 0, "(file missing: " & path & ")", "", "", False
        Exit Sub
    End If

    caseNum = 0
    For Each raw In dataLines
        caseNum = caseNum + 1
        cols = Split(CStr(raw), vbTab)
        If UBound(cols) < 1 Then
            WriteResult wsOut, SUITE_FINGERPRINT, caseNum, CStr(raw), "(2 columns)", "(malformed vector line)", False
        Else
            inputStr = VectorUnescape(cols(0))
            expected = cols(1)
            actual = modSysUtils.ArContentFingerprint(inputStr)
            WriteResult wsOut, SUITE_FINGERPRINT, caseNum, cols(0), expected, actual, (actual = expected)
        End If
    Next raw
End Sub

Private Sub RunParserSuite(ByVal wsOut As Worksheet, ByVal path As String)
    Dim dataLines As Collection
    Dim raw As Variant
    Dim cols() As String
    Dim caseNum As Long
    Dim inputStr As String
    Dim expectedSig As String
    Dim actualSig As String

    Dim ok As Boolean
    Dim bk As String, ct As String, ot As String, nt As String
    Dim ac As String, cf As String
    Dim av As Variant
    Dim verdict As String
    Dim reason As String
    Dim avS As String

    Set dataLines = ReadVectorLines(path)
    If dataLines Is Nothing Then
        WriteResult wsOut, SUITE_PARSER, 0, "(file missing: " & path & ")", "", "", False
        Exit Sub
    End If

    caseNum = 0
    For Each raw In dataLines
        caseNum = caseNum + 1
        cols = Split(CStr(raw), vbTab)
        If UBound(cols) < 9 Then
            WriteResult wsOut, SUITE_PARSER, caseNum, CStr(raw), "(10 columns)", "(malformed vector line)", False
            GoTo NextCase
        End If

        inputStr = VectorUnescape(cols(0))

        ok = modReviewImport.ParseJsonLine(inputStr, bk, ct, ot, nt, ac, av, cf)
        If Not ok Then
            verdict = "REJECT"
            reason = "PARSE"
        Else
            reason = modReviewImport.ValidateParsedChange(bk, ct, ot, nt, ac)
            verdict = IIf(Len(reason) = 0, "PASS", "REJECT")
        End If
        If IsEmpty(av) Then
            avS = ""
        Else
            avS = IIf(CBool(av), "true", "false")
        End If

        ' Compare the full signature: verdict, reason, then every field.
        expectedSig = cols(1) & "|" & cols(2) & "|" & cols(3) & "|" & cols(4) & "|" & _
                      cols(5) & "|" & cols(6) & "|" & cols(7) & "|" & cols(8) & "|" & cols(9)
        actualSig = verdict & "|" & reason & "|" & VectorEscape(bk) & "|" & VectorEscape(ct) & "|" & _
                    VectorEscape(ot) & "|" & VectorEscape(nt) & "|" & VectorEscape(ac) & "|" & _
                    avS & "|" & VectorEscape(cf)

        WriteResult wsOut, SUITE_PARSER, caseNum, cols(0), expectedSig, actualSig, (actualSig = expectedSig)
NextCase:
    Next raw
End Sub

Private Sub RunSessionSuite(ByVal wsOut As Worksheet, ByVal path As String)
    Dim dataLines As Collection
    Dim raw As Variant
    Dim cols() As String
    Dim caseNum As Long
    Dim payload As String
    Dim token As String
    Dim parts() As String
    Dim rawArr() As String
    Dim filtered() As String
    Dim m As Long
    Dim j As Long
    Dim okGate As Boolean
    Dim failCode As String
    Dim expectedSig As String
    Dim actualSig As String

    Set dataLines = ReadVectorLines(path)
    If dataLines Is Nothing Then
        WriteResult wsOut, SUITE_SESSION, 0, "(file missing: " & path & ")", "", "", False
        Exit Sub
    End If

    caseNum = 0
    For Each raw In dataLines
        caseNum = caseNum + 1
        cols = Split(CStr(raw), vbTab)
        If UBound(cols) < 4 Then
            WriteResult wsOut, SUITE_SESSION, caseNum, CStr(raw), "(5 columns)", "(malformed vector line)", False
            GoTo NextCase
        End If

        token = cols(1)
        payload = VectorUnescape(cols(2))

        ' Collect payload lines exactly as the importer does: split on LF into
        ' raw 1-based lines, then run the shared fence-tolerant filter.
        parts = Split(payload, vbLf)
        ReDim rawArr(1 To UBound(parts) - LBound(parts) + 1)
        For j = LBound(parts) To UBound(parts)
            rawArr(j - LBound(parts) + 1) = parts(j)
        Next j
        m = modReviewImport.FilterPayloadLines(rawArr, UBound(parts) - LBound(parts) + 1, filtered)

        failCode = ""
        okGate = modReviewImport.CheckSessionGate(filtered, m, token, failCode)

        expectedSig = cols(3) & "|" & cols(4)
        actualSig = IIf(okGate, "PASS", "FAIL") & "|" & failCode

        WriteResult wsOut, SUITE_SESSION, caseNum, cols(0) & ": " & cols(2), expectedSig, actualSig, (actualSig = expectedSig)
NextCase:
    Next raw
End Sub

' Coverage suite: each line is
'   comment_ids_csv <TAB> edits(ct:bid;...) <TAB> unaddressed_csv <TAB> status
Private Sub RunCoverageSuite(ByVal wsOut As Worksheet, ByVal path As String)
    Dim dataLines As Collection
    Dim raw As Variant
    Dim cols() As String
    Dim caseNum As Long
    Dim ids() As String
    Dim idCount As Long
    Dim changeTypes() As String
    Dim bookmarks() As String
    Dim editCount As Long
    Dim editPairs() As String
    Dim kv() As String
    Dim j As Long
    Dim actualUnaddr As String
    Dim actualStatus As String
    Dim expectedSig As String
    Dim actualSig As String

    Set dataLines = ReadVectorLines(path)
    If dataLines Is Nothing Then
        WriteResult wsOut, SUITE_COVERAGE, 0, "(file missing: " & path & ")", "", "", False
        Exit Sub
    End If

    caseNum = 0
    For Each raw In dataLines
        caseNum = caseNum + 1
        ' Use -1 limit semantics: keep empty trailing fields. Split keeps them.
        cols = Split(CStr(raw), vbTab)
        If UBound(cols) < 3 Then
            WriteResult wsOut, SUITE_COVERAGE, caseNum, CStr(raw), "(4 columns)", "(malformed vector line)", False
            GoTo NextCase
        End If

        idCount = modReviewImport.SplitCsv(cols(0), ids)

        ' Parse the edits column "ct:bid;ct:bid" into parallel arrays.
        editCount = 0
        If Len(cols(1)) > 0 Then
            editPairs = Split(cols(1), ";")
            ReDim changeTypes(1 To UBound(editPairs) - LBound(editPairs) + 1)
            ReDim bookmarks(1 To UBound(editPairs) - LBound(editPairs) + 1)
            For j = LBound(editPairs) To UBound(editPairs)
                kv = Split(editPairs(j), ":")
                editCount = editCount + 1
                changeTypes(editCount) = kv(0)
                If UBound(kv) >= 1 Then bookmarks(editCount) = kv(1) Else bookmarks(editCount) = ""
            Next j
        Else
            ReDim changeTypes(1 To 1)
            ReDim bookmarks(1 To 1)
        End If

        actualUnaddr = modReviewImport.ComputeUnaddressed(ids, idCount, changeTypes, bookmarks, editCount)
        actualStatus = IIf(Len(actualUnaddr) = 0, "ALL_ADDRESSED", "UNADDRESSED")

        expectedSig = cols(2) & "|" & cols(3)
        actualSig = actualUnaddr & "|" & actualStatus

        WriteResult wsOut, SUITE_COVERAGE, caseNum, cols(0) & " / " & cols(1), expectedSig, actualSig, (actualSig = expectedSig)
NextCase:
    Next raw
End Sub

'=== Plumbing ========================================================

Private Function EnsureSelfTestSheet() As Worksheet
    Dim ws As Worksheet

    On Error Resume Next
    Set ws = ThisWorkbook.Worksheets("SelfTest")
    On Error GoTo 0

    If ws Is Nothing Then
        Set ws = ThisWorkbook.Worksheets.Add(After:=ThisWorkbook.Worksheets(ThisWorkbook.Worksheets.Count))
        ws.name = "SelfTest"
    Else
        ws.Cells.Clear
    End If

    ws.Range("A1").value = "Suite"
    ws.Range("B1").value = "Case"
    ws.Range("C1").value = "Input (escaped, <=80 chars)"
    ws.Range("D1").value = "Expected"
    ws.Range("E1").value = "Actual"
    ws.Range("F1").value = "Verdict"
    ws.Range("A1:F1").Font.Bold = True

    Set EnsureSelfTestSheet = ws
End Function

' Reads a vector file with native VBA line I/O (files are pure ASCII by
' construction). Skips blank lines and # comment lines. Returns Nothing if
' the file does not exist.
Private Function ReadVectorLines(ByVal path As String) As Collection
    Dim f As Integer
    Dim s As String
    Dim col As New Collection

    If Len(Dir$(path, vbNormal)) = 0 Then Exit Function

    f = FreeFile
    Open path For Input As #f
    Do While Not EOF(f)
        Line Input #f, s
        If Len(s) > 0 Then
            If Left$(s, 1) <> "#" Then col.Add s
        End If
    Loop
    Close #f

    Set ReadVectorLines = col
End Function

Private Sub WriteResult(ByVal wsOut As Worksheet, ByVal suite As String, _
                        ByVal caseNum As Long, ByVal inputPreview As String, _
                        ByVal expected As String, ByVal actual As String, _
                        ByVal passed As Boolean)
    If Len(inputPreview) > 80 Then inputPreview = Left$(inputPreview, 77) & "..."

    wsOut.Cells(mResultsRow, 1).value = suite
    wsOut.Cells(mResultsRow, 2).value = caseNum
    wsOut.Cells(mResultsRow, 3).value = inputPreview
    wsOut.Cells(mResultsRow, 4).value = expected
    wsOut.Cells(mResultsRow, 5).value = actual
    wsOut.Cells(mResultsRow, 6).value = IIf(passed, "PASS", "FAIL")
    If Not passed Then wsOut.Cells(mResultsRow, 6).Font.Bold = True
    mResultsRow = mResultsRow + 1

    If passed Then
        mSuitePass = mSuitePass + 1
    Else
        mSuiteFail = mSuiteFail + 1
        mReport = mReport & "FAIL " & suite & " #" & caseNum & vbCrLf & _
                  "  input:    " & inputPreview & vbCrLf & _
                  "  expected: " & expected & vbCrLf & _
                  "  actual:   " & actual & vbCrLf
    End If
End Sub

Private Function SuiteSummaryLine(ByVal suite As String) As String
    SuiteSummaryLine = suite & ": " & mSuitePass & " passed, " & mSuiteFail & " failed" & vbCrLf
End Function

'=== Vector escape codec (twin: vector_escape/vector_unescape in =====
'=== tests/vectors/regenerate.py) ====================================

Public Function VectorUnescape(ByVal s As String) As String
    Dim i As Long
    Dim n As Long
    Dim ch As String
    Dim esc As String
    Dim sb As String
    Dim code As Long

    n = Len(s)
    i = 1
    Do While i <= n
        ch = Mid$(s, i, 1)
        If ch = "\" And i < n Then
            esc = Mid$(s, i + 1, 1)
            Select Case esc
                Case "t"
                    sb = sb & vbTab
                    i = i + 2
                Case "n"
                    sb = sb & vbLf
                    i = i + 2
                Case "r"
                    sb = sb & vbCr
                    i = i + 2
                Case "\"
                    sb = sb & "\"
                    i = i + 2
                Case "u"
                    If i + 5 <= n Then
                        ' "&H...&": the trailing ampersand forces a Long so
                        ' 4-digit hex values >= 8000 do not flip negative.
                        code = CLng("&H" & Mid$(s, i + 2, 4) & "&")
                        sb = sb & ChrW(code)
                        i = i + 6
                    Else
                        sb = sb & esc
                        i = i + 2
                    End If
                Case Else
                    sb = sb & esc
                    i = i + 2
            End Select
        Else
            sb = sb & ch
            i = i + 1
        End If
    Loop

    VectorUnescape = sb
End Function

Public Function VectorEscape(ByVal s As String) As String
    Dim i As Long
    Dim code As Long
    Dim sb As String

    For i = 1 To Len(s)
        code = AscW(Mid$(s, i, 1)) And &HFFFF&
        Select Case code
            Case &H5C
                sb = sb & "\\"
            Case &H9
                sb = sb & "\t"
            Case &HA
                sb = sb & "\n"
            Case &HD
                sb = sb & "\r"
            Case &H20 To &H7E
                sb = sb & ChrW(code)
            Case Else
                sb = sb & "\u" & Right$("0000" & Hex$(code), 4)
        End Select
    Next i

    VectorEscape = sb
End Function
