// Regression test against fixtures/golden/*.md, generated by running the actual
// ref/redline-to-markdown.html in a browser on each fixture (with "Annotate edit
// authors" checked -- visible from the {>>--Reviewer A<<} author tags in
// tracked-changes.md/stressor.md). These goldens are READ-ONLY: never regenerate or
// edit them to make this test pass. A failure here means export.js's output actually
// changed, not that the golden is stale.
import { readFileSync, readdirSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { DOMParser } from "@xmldom/xmldom";
import { describe, expect, it } from "vitest";
import { exportDocx } from "../src/ooxml/export.js";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const fixturesDir = path.join(root, "fixtures");
const goldenDir = path.join(fixturesDir, "golden");

// The reference impl doesn't handle fields or content controls at all (it silently
// drops their text). export.js adds the locked ⟦field: ...⟧ / inner-text placeholder
// spec §5.3 requires, which is a deliberate, spec-mandated extension beyond what the
// golden (captured from the reference impl) can reflect. Documented exception, not a
// silent skip -- see the dedicated test below.
const KNOWN_DIVERGENCE = "fields-and-content-controls";

function loadDocx(name) {
  const buf = readFileSync(path.join(fixturesDir, `${name}.docx`));
  return buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength);
}

const goldenNames = readdirSync(goldenDir)
  .filter((f) => f.endsWith(".md"))
  .map((f) => f.replace(/\.md$/, ""));

describe("golden fixture coverage", () => {
  it("every golden has a matching .docx fixture, and vice versa (minus the documented exception)", () => {
    const docxNames = readdirSync(fixturesDir)
      .filter((f) => f.endsWith(".docx"))
      .map((f) => f.replace(/\.docx$/, ""));
    expect(goldenNames.sort()).toEqual(docxNames.sort());
    expect(goldenNames).toContain(KNOWN_DIVERGENCE);
  });
});

describe("export.js matches the reference impl's real browser output byte-for-byte", () => {
  for (const name of goldenNames.filter((n) => n !== KNOWN_DIVERGENCE)) {
    it(`${name}.docx`, async () => {
      const golden = readFileSync(path.join(goldenDir, `${name}.md`), "utf8");
      const { markdown } = await exportDocx(loadDocx(name), {
        DOMParserImpl: DOMParser,
        filename: name,
        annotate: true,
      });
      expect(markdown).toBe(golden);
    });
  }
});

describe(`${KNOWN_DIVERGENCE}.docx (documented exception)`, () => {
  it("does NOT match the golden -- export.js adds locked field/content-control placeholders (spec §5.3) that the reference impl never renders", async () => {
    const golden = readFileSync(path.join(goldenDir, `${KNOWN_DIVERGENCE}.md`), "utf8");
    const { markdown } = await exportDocx(loadDocx(KNOWN_DIVERGENCE), {
      DOMParserImpl: DOMParser,
      filename: KNOWN_DIVERGENCE,
      annotate: true,
    });
    expect(markdown).not.toBe(golden);
    expect(markdown).toContain("⟦field: 3⟧");
    expect(markdown).toContain("TSA-2026-0042");
    // Everything outside the field/content-control placeholders is still identical --
    // the divergence is additive, not a wholesale rewrite.
    expect(markdown).toContain("Page reference: ⟦field: 3⟧ of the source document.");
    expect(golden).toContain("Page reference:  of the source document.");
  });
});
